### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by Tianshi-Xu** [lilujunai/EMQ-series#5]
Hi, how can I run this code? Is there any illustration?

**Comment by liuyiming199721** [comment]
您运行了此代码吗？

**Comment by Tianshi-Xu** [comment]
> 您运行了此代码吗？

没有，我采取了别的方案 (HAWQ)

**Comment by liuyiming199721** [comment]
> > 您运行了此代码吗？
> 
> 没有，我采取了其他方案（HAWQ）

我只是要里面的图可以生成，HAWQ有生成图的代码吗？
